apiVersion: apps/v1
kind: Deployment
metadata:
 name: influxdb3
 namespace: iplon-app-dev
spec:
 selector:
    matchLabels:
     app: influxdb3
 template:
   metadata:
     name: influxdb3
     labels:
       app: influxdb3
   spec:
     containers:
     - name: influxdb3
       image: harbour.iplon.co.in/influxdb/v01
       ports:
       - name: influxdb3
         containerPort: 8086
     imagePullSecrets:
       - name: harbor
         
---

apiVersion: v1
kind: Service
metadata:
 name: influxdb3
 namespace: iplon-app-dev
spec:
 type: NodePort
 selector:
   app: influxdb3
 ports:
   - port: 8086
     targetPort: 8086
     nodePort: 32099
