apiVersion: apps/v1
kind: Deployment
metadata:
 name: nodered
 namespace: iplon-app-dev
spec:
 selector:
    matchLabels:
     app: nodered
 template:
   metadata:
     name: nodered
     labels:
       app: nodered
   spec:
     containers:
     - name: nodered
       image: harbour.iplon.co.in/nodered-dev/nodered/dev
       ports:
       - name: nodered
         containerPort: 1880
     imagePullSecrets:
       - name: harbor
         
---

apiVersion: v1
kind: Service
metadata:
 name: nodered
 namespace: iplon-app-dev
spec:
 type: NodePort
 selector:
   app: nodered
 ports:
   - port: 1880
     targetPort: 1880
     nodePort: 32081
